name: Todoist Readme

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"    # hourly is safer than every minute

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: PravinRaj01/todoist-readme@master  # <- your fork here
        with:
          TODOIST_API_KEY: ${{ secrets.TODOIST_API_KEY }}
